### ISSUE TITLE
Week of 1/15 Plan

### ISSUE THREAD

**Issue by brett-k-cs** [Allen-ISD-Computer-Science/REPO_EagleEngagement_2024#30]
### Sprint:
- [x] Make separate issues for all "work" checklist items
- [x] Verify designations are acceptable for all group members / edit them.
- [x] Go over goals for rest of week

### Work
- **Backend**
  - [x] Look over database schema and get approval from members (minus authentication). #31 
  - [x] Finalize how login will be handled (will likely have to talk with BY and/or contact) #23 
  - [x] #34
- **Frontend**
  - [x] Finalize website design #21 
  - [x] #36
  - [x] #35
- **Android**
  - [x] Setup Android development environment (Android Studio?) and add run/compile documentation #1 
  - [x] #37
  - (a **stretch goal**) ~~get basic navigation working for all pages. #32~~
- **iOS**
  - [ ] Use research from last week to get all screens imported into a mobile app. #33 
  - [ ] Setup IOS development enviroment and figure out xcode, and add run/compile documentation #1 
  - [x] Get a basic template copied into a folder names ios/ in the repository on the correct branch #3.

## Designations
_Note everyone can and probably will help on things they are not listed under, just here to start planning around._
### Backend
- Logan
- Brett

### Frontend
- Brett
- Layne

### Android
- Layne

### iOS
- Logan

**Comment by brett-k-cs** [comment]
### Sprint Meeting Summary:

Talked about development branching & @Logan-Rohlfs came up with the system to update development branch every beginning of week and distribute all changes across the subdevelopment branches. He will be responsible for that as Release Manager. [Done for this week]

Talked about the environmental variables & staging versus production environment for the databases. We will be doing work in the staging environment from now on.

Talked about database schema. Got approval from all members (excluding user authentication).

**Comment by Logan-Rohlfs** [comment]
**Sprint meeting check boxes:**

The check boxes next to each task within the checklist will only be checked off once it is reviewed within an end of week meeting. For each sub task the issue can be submitted when work is done prior to approval
